export const PHASES = [
  {
    id: 1,
    number: '01',
    title: 'Qui es-tu vraiment ?',
    subtitle: 'Fondation',
    color: '#C9A84C',
    xpReward: 200,
    description: 'Découvrir les couches profondes de ton identité avant tout conditionnement social.',
    frameworks: ['Big Five OCEAN', 'Hiérarchie des valeurs', 'MBTI'],
    tools: ['bigfive'],
    questions: [
      {
        id: 'p1_flow_moments',
        text: 'Décris 3 moments de ta vie où tu étais tellement absorbé dans une activité que tu perdais la notion du temps.',
        hint: 'Pense à des moments précis — pas des généralités. Quel âge avais-tu ? Où étais-tu ? Que faisais-tu exactement ?',
        deep: true,
      },
      {
        id: 'p1_natural_value',
        text: 'Quelle valeur les autres te reconnaissent-ils naturellement, sans que tu aies à te justifier ?',
        hint: 'Ce que tes amis, collègues ou famille disent de toi spontanément. Pas ce que tu espères qu\'ils disent.',
        deep: true,
      },
      {
        id: 'p1_no_money',
        text: 'Si l\'argent n\'existait pas, que ferais-tu de tes journées ?',
        hint: 'Sois précis. Pas "voyager" — qu\'est-ce que tu ferais réellement heure par heure ?',
        deep: false,
      },
      {
        id: 'p1_pride',
        text: 'Quelle est la chose que tu as créée ou accomplie dont tu es le plus fier ? Décris pourquoi ça compte autant.',
        hint: 'La fierté révèle les valeurs profondes. Pas forcément un succès public — peut-être quelque chose de privé.',
        deep: true,
      },
      {
        id: 'p1_childhood',
        text: 'Quels comportements ou activités adorais-tu enfant, avant de te soucier du regard des autres ?',
        hint: 'Avant 10 ans, avant l\'école secondaire. Ce que tu faisais pour le plaisir pur, sans chercher validation.',
        deep: false,
      },
      {
        id: 'p1_values',
        text: 'Liste tes 5 valeurs les plus importantes. Puis, quelle est la valeur n°1 que tu ne sacrifierais jamais ?',
        hint: 'Exemples : liberté, impact, famille, créativité, justice, excellence, connexion, aventure...',
        deep: false,
      },
    ],
  },
  {
    id: 2,
    number: '02',
    title: 'Ce qui te fait vibrer',
    subtitle: 'Passion & Flow',
    color: '#B85C38',
    xpReward: 220,
    description: 'Identifier les activités et sujets qui activent ton énergie de façon naturelle.',
    frameworks: ['Flow de Csikszentmihalyi', 'Matrice Énergie × Compétence', 'Roue de la vie'],
    tools: ['energymatrix'],
    questions: [
      {
        id: 'p2_flow_recent',
        text: 'Décris 5 moments de flow récents (dans les 6 derniers mois). Qu\'avais-tu en commun dans chacun ?',
        hint: 'Flow = totalement absorbé, temps qui file, performance naturelle, satisfaction intrinsèque.',
        deep: true,
      },
      {
        id: 'p2_obsession',
        text: 'Quels sujets recherches-tu spontanément, sans qu\'on te le demande ? Sur quoi passes-tu du temps bénévolement ?',
        hint: 'Les sujets sur lesquels tu lis des livres, des articles, des vidéos — pas par obligation mais par pur intérêt.',
        deep: true,
      },
      {
        id: 'p2_world_problem',
        text: 'Quel problème dans le monde t\'énerve ou t\'anime viscéralement ? Pourquoi ce problème-là et pas un autre ?',
        hint: 'Pas le problème "correct" à mentionner — le problème qui te fait vraiment réagir quand tu en parles.',
        deep: false,
      },
      {
        id: 'p2_expert_5y',
        text: 'Dans quel domaine veux-tu être reconnu comme expert dans 5 ans ? Qu\'est-ce qui t\'y attire ?',
        hint: 'Si quelqu\'un te cherchait pour son expertise, dans quel domaine voudrais-tu être cette personne ?',
        deep: false,
      },
      {
        id: 'p2_energy_drain',
        text: 'Quelles activités te vident systématiquement d\'énergie, même quand tu les fais bien ?',
        hint: 'Distinguer compétence et passion. On peut être bon à quelque chose qui nous épuise.',
        deep: false,
      },
    ],
  },
  {
    id: 3,
    number: '03',
    title: 'Ce que tu sais vraiment faire',
    subtitle: 'Compétences',
    color: '#4A7C59',
    xpReward: 240,
    description: 'Cartographier tes compétences réelles et ta combinaison rare de talents.',
    frameworks: ['Méthode SAR', 'Compétence signature', 'Échelle de conscience'],
    tools: [],
    questions: [
      {
        id: 'p3_accomplishments',
        text: 'Liste 10 accomplissements dont tu es fier (pro et perso). Pour chacun, note l\'action précise que TU as prise.',
        hint: 'Format SAR : Situation → Action → Résultat. Sois honnête sur ce que TU as fait, pas l\'équipe.',
        deep: true,
      },
      {
        id: 'p3_natural_skills',
        text: 'Quelles compétences les autres te demandent-ils d\'utiliser pour les aider ? Quand vient-on te chercher ?',
        hint: 'Ce pour quoi on t\'appelle naturellement. Pas ce que tu voudrais faire — ce qu\'on te demande déjà.',
        deep: true,
      },
      {
        id: 'p3_fast_learning',
        text: 'Dans quels domaines apprends-tu anormalement vite par rapport aux autres ? Pourquoi selon toi ?',
        hint: 'Apprentissage rapide = indicateur de talent naturel. Compare-toi à ceux qui démarrent au même niveau.',
        deep: false,
      },
      {
        id: 'p3_teach',
        text: 'Qu\'est-ce que tu pourrais enseigner dès demain à un débutant, pendant 2 heures, sans préparation ?',
        hint: 'Si tu pouvais donner une conférence ou un atelier demain, sur quoi serais-tu crédible immédiatement ?',
        deep: false,
      },
      {
        id: 'p3_signature',
        text: 'Quelle est ta combinaison unique de 2-3 compétences que peu de gens possèdent simultanément ?',
        hint: 'Ex : "analyser des données complexes + communiquer clairement à des non-experts + empathie client". C\'est ton avantage rare.',
        deep: true,
      },
    ],
  },
  {
    id: 4,
    number: '04',
    title: 'Ce pour quoi on te paiera',
    subtitle: 'Marché',
    color: '#7C6FAC',
    xpReward: 260,
    description: 'Comprendre comment ta valeur unique se traduit en proposition commerciale concrète.',
    frameworks: ['3 types de problèmes payants', 'Formule d\'offre', 'Validation marché'],
    tools: [],
    questions: [
      {
        id: 'p4_problem_solved',
        text: 'Quel problème concret et précis peux-tu résoudre pour quelqu\'un ? Décris la douleur de cette personne.',
        hint: 'Pas "j\'aide les gens à être plus heureux". Quel problème spécifique, pour qui exactement, avec quel résultat mesurable ?',
        deep: true,
      },
      {
        id: 'p4_proof',
        text: 'Quelle preuve concrète as-tu déjà créé de la valeur pour quelqu\'un ? Décris un exemple précis.',
        hint: 'Un ami que tu as aidé, un projet freelance, un résultat quantifiable. Même petit — l\'important c\'est que ça existe.',
        deep: false,
      },
      {
        id: 'p4_target',
        text: 'Décris ton client/employeur idéal avec précision : qui est-il ? Quel problème a-t-il ? Qu\'est-ce qui le maintient éveillé la nuit ?',
        hint: 'Sois précis : âge, situation, contexte, frustrations. Pas "des entreprises" — des personnes réelles avec des problèmes réels.',
        deep: true,
      },
      {
        id: 'p4_pitch',
        text: 'Sur une échelle de 1 à 10, à quel point pourrais-tu pitcher ta valeur à un ami aujourd\'hui ? Qu\'est-ce qui manque pour atteindre 10 ?',
        hint: 'Honnêteté absolue. 7 = "je saurais quoi dire mais je manque de preuves". 4 = "je ne saurais pas par où commencer".',
        deep: false,
      },
      {
        id: 'p4_monetized',
        text: 'As-tu déjà été payé pour quelque chose qui te plaisait vraiment ? Même symboliquement ? Décris.',
        hint: 'Même 50€, même un échange de service. Cette preuve de concept est précieuse.',
        deep: false,
      },
    ],
  },
  {
    id: 5,
    number: '05',
    title: 'Ton Ikigai',
    subtitle: 'Convergence',
    color: '#C9A84C',
    xpReward: 280,
    description: 'Trouver l\'intersection précise entre ce que tu aimes, ce dont tu es capable, et ce qui a de la valeur.',
    frameworks: ['Ikigai', '4 archétypes', 'Signaux d\'alignement'],
    tools: ['archetypes', 'ikigai'],
    questions: [
      {
        id: 'p5_intersection',
        text: 'Quelle activité se trouve à l\'intersection de : ce que tu aimes, ce pour quoi tu es doué, ce dont le monde a besoin, et ce pour quoi on te paie ?',
        hint: 'C\'est l\'ikigai. Peut être une formulation en une phrase. Laisse-toi du temps pour réfléchir.',
        deep: true,
      },
      {
        id: 'p5_monetized_love',
        text: 'As-tu une compétence que tu as déjà monétisée ET que tu adores utiliser ? Si oui, décris-la.',
        hint: 'C\'est le signe le plus fort. Si elle existe, tu as une piste très concrète.',
        deep: false,
      },
      {
        id: 'p5_client_type',
        text: 'Quel type de personne ou d\'organisation aimes-tu le plus aider ? Avec qui travailles-tu de façon naturellement énergisante ?',
        hint: 'Le client parfait n\'est pas juste "quelqu\'un qui paie" — c\'est quelqu\'un avec qui la collaboration est elle-même stimulante.',
        deep: false,
      },
      {
        id: 'p5_vision_70',
        text: 'À 70 ans, satisfait de ta vie professionnelle, qu\'est-ce que tu aurais accompli ? Quelle phrase résumerait ta contribution ?',
        hint: 'Pas une liste de succès — une phrase. Qu\'est-ce qui compte vraiment quand tu regardes en arrière à 70 ans ?',
        deep: true,
      },
      {
        id: 'p5_alignment',
        text: 'Quand ressens-tu que tu es "à ta place" dans ton travail ? Quels signaux physiques ou émotionnels te l\'indiquent ?',
        hint: 'Le corps sait avant le mental. Énergie, légèreté, focus, fierté — quand ces signaux apparaissent-ils dans ton travail ?',
        deep: false,
      },
    ],
  },
  {
    id: 6,
    number: '06',
    title: 'Plan d\'action',
    subtitle: 'Exécution',
    color: '#B85C38',
    xpReward: 300,
    description: 'Transformer les insights en actions concrètes et irréversibles cette semaine.',
    frameworks: ['7 étapes d\'exécution', 'Erreurs fatales à éviter'],
    tools: [],
    questions: [
      {
        id: 'p6_hypothesis',
        text: 'Formule ton hypothèse de vocation en 1 phrase : "Je crois que ma vocation est de _____ pour _____, en utilisant _____."',
        hint: 'Pas la version parfaite — la version honnête d\'aujourd\'hui. Elle évoluera. L\'important c\'est de la poser.',
        deep: true,
      },
      {
        id: 'p6_first_action',
        text: 'Quelle est la première action concrète que tu peux faire CETTE SEMAINE pour tester cette hypothèse ?',
        hint: 'Une action = un verbe + un objet + une date. Ex : "Appeler 3 personnes dans ce domaine d\'ici vendredi."',
        deep: true,
      },
      {
        id: 'p6_obstacle',
        text: 'Quel est l\'obstacle RÉEL et précis qui pourrait t\'empêcher de faire ce premier pas ? (Pas une peur générale — un obstacle spécifique.)',
        hint: 'Distinguer les vrais obstacles (temps, argent, accès) des fausses excuses. Sois impitoyablement honnête.',
        deep: false,
      },
      {
        id: 'p6_anti_fatal',
        text: 'Quelle est l\'erreur que tu as tendance à faire quand tu démarres quelque chose de nouveau ? Comment vas-tu l\'éviter cette fois ?',
        hint: 'Procrastination, perfectionnisme, abandon rapide, over-planning sans exécution... Quelle est ton pattern habituel ?',
        deep: false,
      },
      {
        id: 'p6_commitment',
        text: 'Dans 90 jours, à quoi ressemble ta vie si tu as suivi ton plan ? Décris une journée type.',
        hint: 'Visualisation concrète. Pas une liste d\'accomplissements — une journée dans ta vie à J+90. Heure par heure si tu peux.',
        deep: true,
      },
    ],
  },
];

export const OCEAN_DIMENSIONS = [
  {
    id: 'O',
    name: 'Ouverture',
    full: 'Ouverture à l\'expérience',
    low: 'Conventionnel, pratique, prévisible',
    high: 'Curieux, créatif, ouvert aux nouvelles idées',
    color: '#C9A84C',
  },
  {
    id: 'C',
    name: 'Conscienciosité',
    full: 'Conscienciosité',
    low: 'Flexible, spontané, parfois désorganisé',
    high: 'Organisé, discipliné, orienté résultats',
    color: '#4A7C59',
  },
  {
    id: 'E',
    name: 'Extraversion',
    full: 'Extraversion',
    low: 'Introverti, solitaire, réfléchi',
    high: 'Sociable, énergique, affirmatif',
    color: '#B85C38',
  },
  {
    id: 'A',
    name: 'Agréabilité',
    full: 'Agréabilité',
    low: 'Direct, compétitif, sceptique',
    high: 'Empathique, coopératif, confiant',
    color: '#7C6FAC',
  },
  {
    id: 'N',
    name: 'Névrosisme',
    full: 'Stabilité émotionnelle (Névrosisme inversé)',
    low: 'Stable, calme, résistant au stress',
    high: 'Sensible émotionnellement, réactif',
    color: '#5B8DB8',
  },
];

export const ARCHETYPES = [
  {
    id: 'creator',
    name: 'Le Créateur',
    icon: '✦',
    description: 'Tu existes pour donner forme à ce qui n\'existe pas encore. Tu penses en images, en concepts, en possibilités. Ta frustration principale : être contraint à répéter ce qui existe déjà.',
    strengths: ['Pensée originale', 'Vision à long terme', 'Confort avec l\'ambiguïté', 'Innovation'],
    vocations: ['Design', 'Art', 'Écriture', 'Architecture', 'Startup', 'R&D'],
    color: '#C9A84C',
  },
  {
    id: 'builder',
    name: 'Le Bâtisseur',
    icon: '⬡',
    description: 'Tu existes pour transformer les idées en réalités durables. Tu penses en systèmes, en structure, en croissance. Ta frustration principale : les projets qui n\'aboutissent jamais.',
    strengths: ['Exécution', 'Leadership', 'Pensée systémique', 'Persévérance'],
    vocations: ['Entrepreneuriat', 'Management', 'Engineering', 'Consulting', 'Droit'],
    color: '#B85C38',
  },
  {
    id: 'connector',
    name: 'Le Connecteur',
    icon: '◎',
    description: 'Tu existes pour créer des liens entre les personnes, les idées et les ressources. Tu penses en relations et en réseaux. Ta frustration principale : travailler seul sans impact humain.',
    strengths: ['Intelligence sociale', 'Empathie', 'Communication', 'Influence'],
    vocations: ['Vente', 'RH', 'Coaching', 'Diplomatie', 'Marketing', 'Éducation'],
    color: '#4A7C59',
  },
  {
    id: 'optimizer',
    name: 'L\'Optimiseur',
    icon: '▣',
    description: 'Tu existes pour rendre les choses meilleures, plus efficaces, plus précises. Tu penses en processus et en améliorations. Ta frustration principale : le gâchis et l\'inefficacité.',
    strengths: ['Analyse', 'Précision', 'Problem-solving', 'Amélioration continue'],
    vocations: ['Data', 'Finance', 'Opérations', 'Médecine', 'Science', 'Audit'],
    color: '#7C6FAC',
  },
];
